# docker-compose.yml - VERSIÓN CORREGIDA

services:
  backend:
    build: ./backend
    container_name: otakutrack-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo:6
    container_name: otakutrack-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: